<?php

namespace CM\Bundle\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacebookAPIStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookAPIStateRepository extends EntityRepository
{
}
