security:
    encoders:
        CM\Bundle\ModelBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN

    providers:
        administrators:
            entity: { class: CMModelBundle:User }
        #in_memory:
        #    memory:
        #        users:
        #            user:  { name: user, password: user, roles: [ 'ROLE_USER' ] }
        #            admin: { name: admin, password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            

        
                
        login:
            pattern:  ^/login$
            security: false

        session:
            pattern:  ^/session$
            security: false

        api:
            pattern: ^/api
            security: true
            http_basic: true  
            
        recover_password:
            pattern: ^/recoverpasswordpage
            security: false

        recoverPasswordAction: 
            pattern: ^/passwordRecover
            security: false
                         
        secured_area:
            pattern:    .*
            form_login:
                login_path: /login
                check_path: /login_check
                failure_path: null
                use_referer: true
                provider: administrators
            logout:
                path:   logout
                target: /

        
                
        default:
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/session, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recoverpasswordpage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passwordRecover, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        