<?php

namespace CM\Bundle\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FanPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FanPageRepository extends EntityRepository
{
	public function getNames() {
		try {
                $conn = $this->getEntityManager()->getConnection();

                $query = "SELECT fp.name FROM fan_page fp";
                $stmt = $conn->executeQuery($query);
                $stmt->setFetchMode(\PDO::FETCH_COLUMN, 0);
                return $stmt->fetchAll();

            } catch(\PDOException $e) {
                $conn->rollBack();
            }
	}

    public function getFBIds() {
        try {
                $conn = $this->getEntityManager()->getConnection();

                $query = "SELECT fp.fb_id FROM fan_page fp";
                $stmt = $conn->executeQuery($query);
                $stmt->setFetchMode(\PDO::FETCH_COLUMN, 0);
                return $stmt->fetchAll();

            } catch(\PDOException $e) {
                $conn->rollBack();
            }
    }
}
