<?php

namespace CM\Bundle\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FanpageLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FanpageLikeRepository extends EntityRepository
{
	
	public function getFanpageLikeByFecha($desde,$hasta) {
		
       		$query = $this->createQueryBuilder('f');
       		$query->select('f');
       		$query->join('f.fanpage','p');
       		if ($desde and $hasta) {
       			$query->where('substring(f.fecha,1,10) between ?1 and ?2');
       			$query->setParameter(1, $desde);
       			$query->setParameter(2, $hasta); 
       		}
       		else if ($desde) {
       			$query->where('substring(f.fecha,1,10) = ?1 ');
       			$query->setParameter(1, $desde);
       		}
       		
       		$query->orderBy('p.id', 'DESC');
       		return $query->getQuery()->getResult();
		
	}
}

?>